site_name: Yalin(Eric) Yang's Python Notes
site_description: Yalin Yang's Python Learning Notes Sharing 
site_author: Yalin(Eric) Yang
site_url: https://gisyaliny.github.io/python/
copyright: "Copyright &copy; 2024 - 2025 Yalin Yang"

# Repository
repo_name: gisyaliny/python
repo_url: https://github.com/gisyaliny/python

# Configuration
theme:
    language: en
    palette:
        - scheme: default
          #   primary: blue
          accent: indigo
          toggle:
              icon: material/toggle-switch-off-outline
              name: Switch to dark mode
        - scheme: slate
          primary: indigo
          accent: indigo
          toggle:
              icon: material/toggle-switch
              name: Switch to light mode
    name: material
    icon:
        repo: fontawesome/brands/github
    features:
        - navigation.instant
        - navigation.tracking
        - navigation.top
        # - toc.integrate
        # - navigation.tabs
        - navigation.sections
        - search.highlight
        - search.share
    # custom_dir: "docs/overrides"
    font:
        text: Google Sans
        code: Regular

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/gisyaliny/python
    # - icon: fontawesome/brands/google-scholar
      # link: https://scholar.google.com/citations?user=wdkZhlwAAAAJ
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/gisyaliny/
    # - icon: fontawesome/brands/instagram
    #   link: https://www.instagram.com/c17hawke/

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js #?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
    - admonition
    - abbr
    - attr_list
    - def_list
    - footnotes
    - meta
    - md_in_html
    - pymdownx.details
    - pymdownx.mark
    - pymdownx.superfences
    - pymdownx.highlight:
          linenums: true
    - toc:
          permalink: true
  
plugins:
    - search
    - mkdocstrings
    - git-revision-date
    - open-in-new-tab
    - git-revision-date-localized:
          enable_creation_date: true
          type: timeago
    # - pdf-export
    - mkdocs-jupyter:
          include_source: True
          ignore_h1_titles: True
          allow_errors: false
          ignore: ["conf.py"]
          #   execute: True

nav:
    - Home: index.md
    - Foundation:
      - Ch2 Variables: "Foundation/Ch2-Variable-In-Python.ipynb"
      - Ch3 Tuple, List and Dictionary: "Foundation/Ch3-Tuple-List-And-Dictionary.ipynb"
      - Ch5 Functions: "Foundation/Ch5-Functions.ipynb"
      - Ch6 Classes and Objects: "Foundation/Ch6-Classes-And-Objects.ipynb"
      - Ch7 Error and Exception Handling: "Foundation/Ch7-Error-Exception-Handling.ipynb"
    - PostSQL:
      - 01-Connect PostDB: "PostSQL/01_geo_database.ipynb"
      - 02-SQL Basic: "PostSQL/02_SQL_in_Notebook.ipynb"
      - 03-Spatial function in PostGIS: "PostSQL/03_Spatial_Function_PostGIS.ipynb"
      - 04-Spatial relationship query: "PostSQL/04-Spatial-Relationships.ipynb"
      - 05-Projecting data: "PostSQL/05-Projecting-Data.ipynb"
      - 06-Geopandas: "PostSQL/06-geopandas.ipynb"
    - Geoprocessing:
      - Optimal Tessellation: "Geoprocessing/Optimize-GSS-with-tessellation.ipynb"
      - Hexagon Shift: "Geoprocessing/Hexagon_shift.ipynb"
    - PyTest:
      - 01-Unit-Test: "PyTest/01-Python-Unit-Test.ipynb"
      - 02 PyTest Get started: "PyTest/02-Pytest-get-started.ipynb"
      - 03 PyTest Write and Report: "PyTest/03-Pytest-write-and-report-assertions.ipynb"
    - Django:
      - Web application and Tech:
        - Certificate: "Django/01-Web-Application-Technologies-and-Django/Certificate.pdf"
        - Week 1 Lecture: "Django/01-Web-Application-Technologies-and-Django/Week1/Lecture01.pdf"
        - Week 1 Notes: "Django/01-Web-Application-Technologies-and-Django/Week1/Week1.ipynb"
        - Week 1 Django Intro: "Django/01-Web-Application-Technologies-and-Django/Week1/Week1-Intro-Django.pdf"
        - Week 1 Quiz: "Django/01-Web-Application-Technologies-and-Django/Week1/Quiz1.pdf"
        - Week 2 Lecture: "Django/01-Web-Application-Technologies-and-Django/Week2/Week2-Installing-Django.pdf"
        - Week 2 Lecture 02: "Django/01-Web-Application-Technologies-and-Django/Week2/Week-2-Write-Your-First-App.pdf"
        - Week 2 Lecture 03: "Django/01-Web-Application-Technologies-and-Django/Week2/Week2-Run-App-in-PyhonAnyWhere.pdf"
        - Week 2 Quiz: "Django/01-Web-Application-Technologies-and-Django/Week2/Quiz2.pdf"
        - Week 3 Lecture: "Django/01-Web-Application-Technologies-and-Django/Week3/Week3-Hypertext-Markup-Language.pdf"
        - Week 3 Lecture 02: "Django/01-Web-Application-Technologies-and-Django/Week3/Week3-Adding-HTML-Content-to-Django.pdf"
        - Week 3 Quiz: "Django/01-Web-Application-Technologies-and-Django/Week3/Quiz3.pdf"
        - Week 4 Lecture: "Django/01-Web-Application-Technologies-and-Django/Week4/Week4-Cascading-Style-Sheets.pdf"
        - Week 4 Lecture 02: "Django/01-Web-Application-Technologies-and-Django/Week4/Week4-Task.pdf"
        - Week 4 Quiz: "Django/01-Web-Application-Technologies-and-Django/Week4/Quiz4.pdf"
        - Week 5 Lecture: "Django/01-Web-Application-Technologies-and-Django/Week5/Week5-SQL.pdf"
        - Week 5 Quiz: "Django/01-Web-Application-Technologies-and-Django/Week5/Quiz5.pdf"
      - Build Web application:
        - Certificate: "Django/02-Building-Web-Applications-in-Django/Certificate.pdf"
        - Week 1 Lecture: "Django/02-Building-Web-Applications-in-Django/Week1/Week1-1.pdf"
        - Week 1 Lecture 02: "Django/02-Building-Web-Applications-in-Django/Week1/Week1-2.pdf"
        - Week 1 Lecture 03: "Django/02-Building-Web-Applications-in-Django/Week1/Writing-your-first-Django-app-part-2.pdf"
        - Week 1 Quiz: "Django/02-Building-Web-Applications-in-Django/Week1/Quiz1.pdf"
        - Week 2 Lecture: "Django/02-Building-Web-Applications-in-Django/Week2/Built-in-template-tags-and-filters.pdf"
        - Week 2 Lecture 02: "Django/02-Building-Web-Applications-in-Django/Week2/Command-Line-Shell-For-SQLite.pdf"
        - Week 2 Lecture 03: "Django/02-Building-Web-Applications-in-Django/Week2/Writing-your-first-Django-app-part3.pdf"
        - Week 2 Quiz: "Django/02-Building-Web-Applications-in-Django/Week2/Quiz2.pdf"
        - Week 3 Lecture: "Django/02-Building-Web-Applications-in-Django/Week3/Built-in-class-based-generic-views.pdf"
        - Week 3 Lecture 02: "Django/02-Building-Web-Applications-in-Django/Week3/Object-oriented-programming.pdf"
        - Week 3 Quiz: "Django/02-Building-Web-Applications-in-Django/Week3/Quiz3.pdf"
        - Week 4 Lecture: "Django/02-Building-Web-Applications-in-Django/Week4/Writing-your-first-Django-app-part4.pdf"
        - Week 4 Quiz: "Django/02-Building-Web-Applications-in-Django/Week4/Quiz4.pdf"
